import React, { createContext, useContext, useState } from 'react';

const translations = {
  English: {
    appTitle: 'Meal_ResQ',
    tagline: 'Rescuing Food, Enriching Lives',
    selectRoleTitle: 'Choose Your Platform Role',
    donorRole: 'Food Donor',
    ngoRole: 'NGO / Charity',
    volRole: 'Volunteer Dispatch',
    neederRole: 'Person in Need',
    adminRole: 'System Admin',
    signIn: 'Sign In',
    register: 'Register',
    emailOrUser: 'Email Address',

    password: 'Password',
    fullName: 'Full Name / Organization',
    phoneNumber: 'Phone Number (+91)',
    locationAddress: 'Address / Pickup Location',
    forgotPassword: 'Forgot Password?',
    dashboard: 'Dashboard',
    alerts: 'Alerts',
    profile: 'Profile',
    settings: 'Settings',
    availableFood: 'Available Food',
    postFood: '+ Post Food Donation',
    darkTheme: 'Dark Theme',
    prefLang: 'Preferred Language',
    savePref: 'Save Preferences',
    appSettings: 'App Settings',
    selectLangPrompt: 'Select your preferred Indian language',
    rescuedMeals: 'Meals Rescued',
    totalPosted: 'Total Food Posted',
    activePickups: 'Active Pickups',
    activeListings: 'Active Listings',
    liveChat: 'Live Chat',
    yourFoodDonations: 'Your Food Donations',
    trackListings: 'Track active listings and rescued meals',
    noFoodDonationsYet: 'No Food Donations Posted Yet',
    tapPostFoodMsg: "Tap '+ Post Food' above to share surplus meals with nearby NGOs!",
    notificationsAlerts: 'Notifications & Alerts',
    noNotificationsYet: 'No Notifications Yet',
    realtimeNotice: 'Real-time donation claims and pickup alerts will appear here!',
    rescueLiveChat: 'Rescue Live Chat',
    directChatChannel: 'Direct Chat Channel Active',
    connectDirectly: 'Connect directly with food donors, volunteers & NGOs during active pickups!',
    editProfile: 'Edit Profile',
    saveProfile: 'Save Profile',
    viewMode: 'VIEW MODE',
    editingMode: 'EDITING MODE',
    takePhotoCamera: 'Take Photo with Camera 📷',
    chooseGallery: 'Choose from Gallery 🖼️',
    logout: 'Logout',
    aboutApp: 'About Meal-ResQ',
  },
  Hindi: {
    appTitle: 'मील्स रेस्क्यू',
    tagline: 'भोजन बचाएं, जीवन समृद्ध बनाएं',
    selectRoleTitle: 'अपनी भूमिका चुनें',
    donorRole: 'भोजन दाता',
    ngoRole: 'एनजीओ / धर्मार्थ',
    volRole: 'स्वयंसेवक',
    neederRole: 'जरूरतमंद',
    adminRole: 'सिस्टम एडमिन',
    signIn: 'साइन इन करें',
    register: 'पंजीकरण करें',
    emailOrUser: 'ईमेल या उपयोगकर्ता नाम',
    password: 'पासवर्ड',
    fullName: 'पूरा नाम / संस्था',
    phoneNumber: 'फोन नंबर (+91)',
    locationAddress: 'पता / पिकअप स्थान',
    forgotPassword: 'पासवर्ड भूल गए?',
    dashboard: 'डैशबोर्ड',
    alerts: 'सूचनाएं',
    profile: 'प्रोफाइल',
    settings: 'सेटिंग्स',
    availableFood: 'उपलब्ध भोजन',
    postFood: '+ भोजन दान करें',
    darkTheme: 'डार्क थीम',
    prefLang: 'पसंदीदा भाषा',
    savePref: 'प्राथमिकताएं सहेजें',
    appSettings: 'ऐप सेटिंग्स',
    selectLangPrompt: 'अपनी पसंदीदा भारतीय भाषा चुनें',
    rescuedMeals: 'बचाए गए भोजन',
    totalPosted: 'कुल पोस्ट किया गया भोजन',
    activePickups: 'सक्रिय पिकअप',
    activeListings: 'सक्रिय सूचियां',
    liveChat: 'लाइव चैट',
    yourFoodDonations: 'आपके भोजन दान',
    trackListings: 'सक्रिय सूचियों और बचाए गए भोजन को ट्रैक करें',
    noFoodDonationsYet: 'अभी तक कोई भोजन दान पोस्ट नहीं किया गया',
    tapPostFoodMsg: 'पास के एनजीओ के साथ अधिशेष भोजन साझा करने के लिए ऊपर "+ भोजन दान करें" पर टैप करें!',
    notificationsAlerts: 'सूचनाएं एवं अलर्ट',
    noNotificationsYet: 'अभी तक कोई सूचना नहीं',
    realtimeNotice: 'वास्तविक समय के दान के दावे और पिकअप अलर्ट यहां दिखाई देंगे!',
    rescueLiveChat: 'रेस्क्यू लाइव चैट',
    directChatChannel: 'प्रत्यक्ष चैट चैनल सक्रिय',
    connectDirectly: 'सक्रिय पिकअप के दौरान भोजन दाताओं, स्वयंसेवकों और एनजीओ के साथ सीधे जुड़ें!',
    editProfile: 'प्रोफाइल संपादित करें',
    saveProfile: 'प्रोफाइल सहेजें',
    viewMode: 'व्यू मोड',
    editingMode: 'संपादन मोड',
    takePhotoCamera: 'कैमरा से फोटो लें 📷',
    chooseGallery: 'गैलरी से चुनें 🖼️',
    logout: 'लॉगआउट',
    aboutApp: 'मील्स रेस्क्यू के बारे में',
  },
  Telugu: {
    appTitle: 'మీల్_రెస్క్యూ',
    tagline: 'ఆహారాన్ని కాపాడండి, జీవితాలను వెలిగించండి',
    selectRoleTitle: 'మీ పాత్రను ఎంచుకోండి',
    donorRole: 'ఆహార దాత',
    ngoRole: 'ఎన్జీఓ / స్వచ్ఛంద సంస్థ',
    volRole: 'వాలంటీర్',
    neederRole: 'అవసరంలో ఉన్నవారు',
    adminRole: 'సిస్టమ్ అడ్మిన్',
    signIn: 'సైన్ ఇన్',
    register: 'రిజిస్టర్',
    emailOrUser: 'ఈమెయిల్ లేదా యూజర్ నేమ్',
    password: 'పాస్‌వర్డ్',
    fullName: 'పూర్తి పేరు / సంస్థ',
    phoneNumber: 'ఫోన్ నంబర్ (+91)',
    locationAddress: 'చిరునామా / పికప్ లొకేషన్',
    forgotPassword: 'పాస్‌వర్డ్ మర్చిపోయారా?',
    dashboard: 'డాష్‌బోర్డ్',
    alerts: 'అలర్ట్‌లు',
    profile: 'ప్రొఫైల్',
    settings: 'సెట్టింగ్‌లు',
    availableFood: 'అందుబాటులో ఉన్న ఆహారం',
    postFood: '+ ఆహార విరాళం ఇవ్వండి',
    darkTheme: 'డార్క్ థీమ్',
    prefLang: 'ఇష్టమైన భాష',
    savePref: 'అభిరుచులను సేవ్ చేయండి',
    appSettings: 'యాప్ సెట్టింగ్‌లు',
    selectLangPrompt: 'మీ ఇష్టమైన భారతీయ భాషను ఎంచుకోండి',
    rescuedMeals: 'కాపాడిన భోజనాలు',
    totalPosted: 'మొత్తం పోస్ట్ చేసిన ఆహారం',
    activePickups: 'యాక్టివ్ పికప్‌లు',
    activeListings: 'యాక్టివ్ లిస్టింగ్‌లు',
    liveChat: 'లైవ్ చాట్',
    yourFoodDonations: 'మీ ఆహార విరాళాలు',
    trackListings: 'యాక్టివ్ లిస్టింగ్‌లు మరియు కాపాడిన ఆహారాన్ని ట్రాక్ చేయండి',
    noFoodDonationsYet: 'ఇంకా ఆహార విరాళాలు పోస్ట్ చేయలేదు',
    tapPostFoodMsg: 'సమీపంలోని NGOలతో మిగిలిపోయిన ఆహారాన్ని పంచుకోవడానికి పైన "+ ఆహార విరాళం ఇవ్వండి" ని నొక్కండి!',
    notificationsAlerts: 'నోటిఫికేషన్‌లు & అలర్ట్‌లు',
    noNotificationsYet: 'ఇంకా నోటిఫికేషన్‌లు లేవు',
    realtimeNotice: 'రియల్-టైమ్ డొనేషన్ క్లెయిమ్‌లు మరియు పికప్ అలర్ట్‌లు ఇక్కడ కనిపిస్తాయి!',
    rescueLiveChat: 'రెస్క్యూ లైవ్ చాట్',
    directChatChannel: 'డైరెక్ట్ చాట్ ఛానెల్ యాక్టివ్',
    connectDirectly: 'యాక్టివ్ పికప్‌ల సమయంలో డోనార్లు, వాలంటీర్లు మరియు NGOలతో నేరుగా కనెక్ట్ అవ్వండి!',
    editProfile: 'ప్రొఫైల్ ఎడిట్ చేయండి',
    saveProfile: 'ప్రొఫైల్ సేవ్ చేయండి',
    viewMode: 'వ్యూ మోడ్',
    editingMode: 'ఎడిటింగ్ మోడ్',
    takePhotoCamera: 'కెమెరాతో ఫోటో తీయండి 📷',
    chooseGallery: 'గ్యాలరీ నుండి ఎంచుకోండి 🖼️',
    logout: 'లాగౌట్',
    aboutApp: 'మీల్_రెస్క్యూ గురించి',
  },
  Tamil: {
    appTitle: 'மீல்_ரெஸ்கியூ',
    tagline: 'உணவை மீற்போம், உயிர்களைக் காப்போம்',
    selectRoleTitle: 'உங்கள் பங்கைத் தேர்ந்தெடுக்கவும்',
    donorRole: 'உணவு வழங்குபவர்',
    ngoRole: 'தொண்டு நிறுவனம்',
    volRole: 'தன்னார்வலர்',
    neederRole: 'தேவையுள்ளவர்',
    adminRole: 'நிர்வாகி',
    signIn: 'உள்நுழைக',
    register: 'பதிவு செய்க',
    emailOrUser: 'மின்னஞ்சல் அல்லது பயனர் பெயர்',
    password: 'கடவுச்சொல்',
    fullName: 'முழு பெயர் / நிறுவனம்',
    phoneNumber: 'தொலைபேசி எண் (+91)',
    locationAddress: 'முகவரி / பிக்கப் இடம்',
    forgotPassword: 'கடவுச்சொல் மறந்துவிட்டதா?',
    dashboard: 'டாஷ்போர்டு',
    alerts: 'அறிவிப்புகள்',
    profile: 'சுயவிவரம்',
    settings: 'அமைப்புகள்',
    availableFood: 'கிடைக்கும் உணவு',
    postFood: '+ உணவு தானம் செய்க',
    darkTheme: 'இருண்ட தீம்',
    prefLang: 'விருப்பமான மொழி',
    savePref: 'விருப்பங்களைச் சேமி',
    appSettings: 'பயன்பாட்டு அமைப்புகள்',
    selectLangPrompt: 'உங்கள் இந்திய மொழியைத் தேர்ந்தெடுக்கவும்',
    rescuedMeals: 'மீட்கப்பட்ட உணவுகள்',
    totalPosted: 'மொத்த உணவு',
    activePickups: 'செயலில் உள்ள பிக்கப்',
    activeListings: 'செயலில் உள்ளவை',
    liveChat: 'நேரலை அரட்டை',
    yourFoodDonations: 'உங்கள் உணவு நன்கொடைகள்',
    trackListings: 'செயலில் உள்ள பட்டியல்களைக் கண்காணிக்கவும்',
    noFoodDonationsYet: 'இன்னும் உணவு நன்கொடை இல்லை',
    tapPostFoodMsg: 'உணவைப் பகிர மேலே உள்ள பொத்தானைத் தட்டவும்!',
    notificationsAlerts: 'அறிவிப்புகள் & எச்சரிக்கைகள்',
    noNotificationsYet: 'இன்னும் அறிவிப்புகள் இல்லை',
    realtimeNotice: 'நேரலை அறிவிப்புகள் இங்கே தோன்றும்!',
    rescueLiveChat: 'நேரலை அரட்டை',
    directChatChannel: 'நேரடி அரட்டை செயல்படுகிறது',
    connectDirectly: 'உணவு வழங்குபவர்களுடன் நேரடியாக இணையுங்கள்!',
    editProfile: 'சுயவிவரத்தைத் திருத்து',
    saveProfile: 'சுயவிவரத்தைச் சேமி',
    viewMode: 'பார்வை பயன்முறை',
    editingMode: 'திருத்தும் பயன்முறை',
    takePhotoCamera: 'கேமரா மூலம் படம் எடுக்கவும் 📷',
    chooseGallery: 'கேலரியில் இருந்து தேர்ந்தெடுக்கவும் 🖼️',
    logout: 'வெளியேறு',
    aboutApp: 'பயன்பாட்டைப் பற்றி',
  },
  Kannada: {
    appTitle: 'ಮೀಲ್_ರೆಸ್ಕ್ಯೂ',
    tagline: 'ಆಹಾರ ಉಳಿಸಿ, ಜೀವ ಬೆಳಗಿಸಿ',
    selectRoleTitle: 'ನಿಮ್ಮ ಪಾತ್ರವನ್ನು ಆಯ್ಕೆಮಾಡಿ',
    donorRole: 'ಆಹಾರ ದಾನಿ',
    ngoRole: 'ಎನ್‌ಜಿಒ / ಸ್ವಯಂಸೇವಾ ಸಂಸ್ಥೆ',
    volRole: 'ಸ್ವಯಂಸೇವಕ',
    neederRole: 'ಅಗತ್ಯವಿರುವವರು',
    adminRole: 'ಸಿಸ್ಟಮ್ ಅಡ್ಮಿನ್',
    signIn: 'ಸೈನ್ ಇನ್',
    register: 'ನೋಂದಾಯಿಸಿ',
    emailOrUser: 'ಇಮೇಲ್ ಅಥವಾ ಬಳಕೆದಾರ ಹೆಸರು',
    password: 'ಪಾಸ್‌ವರ್ಡ್',
    fullName: 'ಪೂರ್ಣ ಹೆಸರು / ಸಂಸ್ಥೆ',
    phoneNumber: 'ಫೋನ್ ಸಂಖ್ಯೆ (+91)',
    locationAddress: 'ವಿಳಾಸ / ಪಿಕ್‌ಅಪ್ ಸ್ಥಳ',
    forgotPassword: 'ಪಾಸ್‌ವರ್ಡ್ ಮರೆತಿದ್ದೀರಾ?',
    dashboard: 'ಡ್ಯಾಶ್‌ಬೋರ್ಡ್',
    alerts: 'ಎಚ್ಚರಿಕೆಗಳು',
    profile: 'ಪ್ರೊಫೈಲ್',
    settings: 'ಸೆಟ್ಟಿಂಗ್‌ಗಳು',
    availableFood: 'ಲಭ್ಯವಿರುವ ಆಹಾರ',
    postFood: '+ ಆಹಾರ ದಾನ ಮಾಡಿ',
    darkTheme: 'ಡಾರ್ಕ್ ಥೀಮ್',
    prefLang: 'ಆದ್ಯತೆಯ ಭಾಷೆ',
    savePref: 'ಆದ್ಯತೆಗಳನ್ನು ಉಳಿಸಿ',
    appSettings: 'ಆಪ್ ಸೆಟ್ಟಿಂಗ್‌ಗಳು',
    selectLangPrompt: 'ನಿಮ್ಮ ಭಾರತೀಯ ಭಾಷೆಯನ್ನು ಆಯ್ಕೆಮಾಡಿ',
    rescuedMeals: 'ಉಳಿಸಿದ ಊಟಗಳು',
    totalPosted: 'ಒಟ್ಟು ಪೋಸ್ಟ್ ಮಾಡಿದ ಆಹಾರ',
    activePickups: 'ಸಕ್ರಿಯ ಪಿಕ್‌ಅಪ್‌ಗಳು',
    activeListings: 'ಸಕ್ರಿಯ ಪಟ್ಟಿಗಳು',
    liveChat: 'ಲೈವ್ ಚಾಟ್',
    yourFoodDonations: 'ನಿಮ್ಮ ಆಹಾರ ದಾನಗಳು',
    trackListings: 'ಸಕ್ರಿಯ ಪಟ್ಟಿಗಳನ್ನು ಟ್ರ್ಯಾಕ್ ಮಾಡಿ',
    noFoodDonationsYet: 'ಇನ್ನೂ ಯಾವುದೇ ಆಹಾರ ದಾನ ಪೋಸ್ಟ್ ಮಾಡಲಾಗಿಲ್ಲ',
    tapPostFoodMsg: 'ಉಪಹಾರವನ್ನು ಹಂಚಿಕೊಳ್ಳಲು ಮೇಲಿನ ಬಟನ್ ಒತ್ತಿ!',
    notificationsAlerts: 'ಅಧಿಸೂಚನೆಗಳು ಮತ್ತು ಎಚ್ಚರಿಕೆಗಳು',
    noNotificationsYet: 'ಇನ್ನೂ ಯಾವುದೇ ಅಧಿಸೂಚನೆಗಳಿಲ್ಲ',
    realtimeNotice: 'ನೈಜ-ಸಮಯದ ಎಚ್ಚರಿಕೆಗಳು ಇಲ್ಲಿ ಕಾಣಿಸಿಕೊಳ್ಳುತ್ತವೆ!',
    rescueLiveChat: 'ಲೈವ್ ಚಾಟ್',
    directChatChannel: 'ನೇರ ಚಾಟ್ ಚಾನೆಲ್ ಸಕ್ರಿಯ',
    connectDirectly: 'ನೇರವಾಗಿ ಸಂಪರ್ಕಿಸಿ!',
    editProfile: 'ಪ್ರೊಫೈಲ್ ತಿದ್ದುಪಡಿ ಮಾಡಿ',
    saveProfile: 'ಪ್ರೊಫೈಲ್ ಉಳಿಸಿ',
    viewMode: 'ವೀಕ್ಷಣೆ ಮೋಡ್',
    editingMode: 'ಎಡಿಟಿಂಗ್ ಮೋಡ್',
    takePhotoCamera: 'ಕ್ಯಾಮೆರಾದಿಂದ ಫೋಟೋ ತೆಗೆಯಿರಿ 📷',
    chooseGallery: 'ಗ್ಯಾಲರಿಯಿಂದ ಆಯ್ಕೆಮಾಡಿ 🖼️',
    logout: 'ಲಾಗ್‌ಔಟ್',
    aboutApp: 'ಆಪ್ ಬಗ್ಗೆ',
  },
};

const LanguageContext = createContext();

export function LanguageProvider({ children }) {
  const [currentLang, setCurrentLang] = useState('English');

  const changeLanguage = (langName) => {
    if (translations[langName]) {
      setCurrentLang(langName);
    }
  };

  const t = (key) => {
    const langObj = translations[currentLang] || translations.English;
    return langObj[key] || translations.English[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ currentLang, changeLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    return {
      currentLang: 'English',
      changeLanguage: () => {},
      t: (k) => k,
    };
  }
  return context;
}
